name: Build Frontend
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ui:
    name: UI
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Go into the frontend directory
        run: cd frontend
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run:  yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
